version: 2

shared: &shared
  working_directory: ~/repo

  steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run: yarn test
    - run: yarn test:e2e


jobs:
  "node-8.9":
    <<: *shared
    docker:
      - image: node:8.9
  "node-9":
    <<: *shared
    docker:
      - image: node:9

workflows:
  version: 2
  build:
    jobs:
      - "node-8.9"
      - "node-9"
